"""Backward-compatibility shim. Canonical: pgqueuer.core.executors"""

from pgqueuer.core.executors import (
    AbstractEntrypointExecutor,
    AbstractScheduleExecutor,
    AsyncContextEntrypoint,
    AsyncCrontab,
    AsyncEntrypoint,
    BaseRetryWithBackoffExecutor,
    DatabaseRetryWithBackoffEntrypointExecutor,
    Entrypoint,
    EntrypointExecutor,
    EntrypointExecutorParameters,
    EntrypointTypeVar,
    InlineRetryWithBackoffEntrypointExecutor,
    OnTerminalFailure,
    RetryWithBackoffEntrypointExecutor,
    ScheduleExecutor,
    ScheduleExecutorFactoryParameters,
    SyncContextEntrypoint,
    SyncEntrypoint,
    TerminalFailureReason,
    is_async_callable,
)

__all__ = [
    "AbstractEntrypointExecutor",
    "AbstractScheduleExecutor",
    "AsyncContextEntrypoint",
    "AsyncCrontab",
    "AsyncEntrypoint",
    "BaseRetryWithBackoffExecutor",
    "DatabaseRetryWithBackoffEntrypointExecutor",
    "Entrypoint",
    "EntrypointExecutor",
    "EntrypointExecutorParameters",
    "EntrypointTypeVar",
    "InlineRetryWithBackoffEntrypointExecutor",
    "OnTerminalFailure",
    "RetryWithBackoffEntrypointExecutor",
    "ScheduleExecutor",
    "ScheduleExecutorFactoryParameters",
    "SyncContextEntrypoint",
    "SyncEntrypoint",
    "TerminalFailureReason",
    "is_async_callable",
]
